### ISSUE TITLE
[Amadeus] Migrate Reminder

### ISSUE THREAD

**Issue by Czechbol** [pumpkin-py/pumpkin-reminder#1]
We need to migrate the Reminder cog from Amadeus to Reminder (Reminder submodule).

See the cog [here](https://github.com/Czechbol/Amadeus/blob/master/cogs/remindme.py).

The cog uses a database so this will be a moderate difficulty port.

Feel free to rewrite any part of the cog to make it better/more readable

**Comment by sinus-x** [comment]
Resolved by #2
